export enum ServerResponseMessage {
  FORBIDDEN = "FORBIDDEN",
  UNAUTHORIZED = "UNAUTHORIZED",
  NOT_FOUND = "NOT_FOUND",
  UNKNOWN = "UNKNOWN",
  INVALID_TOKEN = "INVALID_TOKEN",
  PRECONDITION_FAILED = "PRECONDITION_FAILED",
}
